const F=[['opening','Opening cash'],['production','Production'],['requested','Sales requested'],['sales','Actual sales allocation'],['price','Price per ice cream'],['milk','Milk tons'],['milkPrice','Milk price per ton'],['market','Marketing'],['rent','Premises rent'],['maintenance','Machine maintenance'],['depreciation','Depreciation'],['transport','Transport per ice cream'],['salary','Salaries'],['loan','New loan'],['interest','Loan interest'],['machine','Machine purchase'],['taxLoss','Unused tax losses']];
const winter={opening:100000,production:50000,requested:50000,sales:50000,price:2,milk:2.5,milkPrice:20000,market:5000,rent:17000,maintenance:1800,depreciation:4375,transport:.1,salary:10000,loan:0,interest:0,machine:35000,taxLoss:0};
let seasons=JSON.parse(localStorage.getItem('ice-seasons')||'{"Y1 Winter":'+JSON.stringify(winter)+'}');let plans=JSON.parse(localStorage.getItem('ice-plans')||'[]');let current={...winter,opening:73546,production:45000,requested:45000,sales:36000,milk:2.25,market:3000,machine:0};
const n=x=>Number(x)||0,m=x=>'Sh '+Math.round(x).toLocaleString();
function calc(p){let rev=p.sales*p.price,milk=p.milk*p.milkPrice,transport=p.sales*p.transport,gross=rev-milk-p.maintenance-p.depreciation,bonus=Math.round(Math.max(gross,0)*.05),pre=gross-transport-p.market-bonus-p.salary-p.rent-p.interest,tax=Math.round(Math.max(0,pre-p.taxLoss)*.1),before=p.opening+p.loan-p.machine-milk-p.market,close=p.opening+p.loan+rev-p.machine-milk-p.market-p.rent-p.maintenance-transport-p.salary-bonus-p.interest-tax;return{profit:pre-tax,close,before,spoil:Math.max(0,p.production-p.sales)}}
function fields(target,obj,onChange){document.querySelector(target).innerHTML=F.map(([k,l])=>`<label>${l}<input type=number step=any data-k=${k} value=${obj[k]??0}></label>`).join('');document.querySelector(target).oninput=e=>{obj[e.target.dataset.k]=n(e.target.value);onChange()}}
function seasonView(){let key=season.value,d=seasons[key]||{...winter,opening:0,production:0,requested:0,sales:0,milk:0,market:0,rent:0,maintenance:0,depreciation:0,salary:0,machine:0};fields('#seasonFields',d,()=>{seasons[key]=d;localStorage.setItem('ice-seasons',JSON.stringify(seasons));summaryView()})}
function summaryView(){let a=Object.values(seasons).map(calc),profit=a.reduce((s,x)=>s+x.profit,0),cash=a.at(-1)?.close||0;summary.innerHTML=`<div><span>Saved seasons</span><b>${a.length}/4</b></div><div><span>Profit so far</span><b>${m(profit)}</b></div><div><span>Latest closing cash</span><b>${m(cash)}</b></div>`}
function risks(p,r){let x=[];if(r.before<0)x.push('cash negative before sales');if(r.close<0)x.push('negative closing cash');if(p.production&&r.spoil/p.production>.2)x.push('high spoilage');if(p.sales<p.requested)x.push('sales below request');if(r.profit<0)x.push('loss');return x}
function planView(){fields('#planFields',current,()=>planResult());planResult()}
function planResult(){let r=calc(current),x=risks(current,r);planOutput.innerHTML=`<div class="stats"><div><span>Net profit</span><b>${m(r.profit)}</b></div><div><span>Closing cash</span><b>${m(r.close)}</b></div><div><span>Unsold production</span><b>${r.spoil.toLocaleString()}</b></div></div><p class="${x.length?'risk':'safe'}">${x.length?'Warnings: '+x.join(' · '):'This plan has no major cash or spoilage warning.'}</p>`}
function compare(){if(!plans.length){table.innerHTML='<p>Save at least two plans to compare them.</p>';chart.innerHTML='';recommendation.innerHTML='';return}let rows=plans.map(p=>({...p,r:calc(p),x:risks(p,calc(p))}));table.innerHTML=rows.map(x=>`<div class="row"><b>${x.name}</b><span>Profit ${m(x.r.profit)}</span><span>Cash ${m(x.r.close)}</span><span>${x.x.length?x.x.length+' warnings':'Safer'}</span></div>`).join('');chart.innerHTML=rows.map(x=>`<div class="bar" style="height:${Math.max(26,Math.min(170,Math.abs(x.r.close)/600))}px">${x.name}<br>${m(x.r.close)}</div>`).join('');let best=rows.sort((a,b)=>a.x.length-b.x.length||b.r.close-a.r.close)[0];recommendation.innerHTML=`<p class="safe"><b>Recommendation: ${best.name}</b> currently looks safest because it has ${best.x.length} warning(s) and closes with ${m(best.r.close)}.</p>`}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='compare')compare()});season.onchange=seasonView;savePlan.onclick=()=>{let name=planName.value.trim()||`Plan ${plans.length+1}`;plans.push({name,...current});localStorage.setItem('ice-plans',JSON.stringify(plans));planName.value='';compare();alert(name+' saved')};seasonView();summaryView();planView();compare();
