const machines={1:{machine:35000,capacity:72000,maintenance:1800,depreciation:4375},2:{machine:95000,capacity:120000,maintenance:2900,depreciation:11875},3:{machine:38000,capacity:68000,maintenance:2100,depreciation:4750},4:{machine:70000,capacity:95000,maintenance:2900,depreciation:8750},5:{machine:28000,capacity:45000,maintenance:1300,depreciation:3500},6:{machine:90000,capacity:110000,maintenance:2900,depreciation:11250}};
const fields=[['machineNo','Machine number (1 to 6)'],['milk','Milk bought tons'],['production','Production units'],['requested','Sales requested'],['sales','Actual sales allocation'],['market','Market investment'],['rent','Premise rent'],['transport','Transport per sold unit'],['loan','New loan'],['term','Loan term seasons']];
const plans={safe:{machineNo:5,milk:2,production:40000,requested:40000,sales:30000,market:1000,rent:10000,transport:.4,loan:0,term:4},growth:{machineNo:2,milk:3,production:60000,requested:60000,sales:40000,market:5000,rent:15000,transport:.2,loan:60000,term:4}};
const money=v=>'Sh '+Math.round(v).toLocaleString();const num=v=>Number(v)||0;
function calc(p){const mData=machines[p.machineNo]||machines[1],revenue=p.sales*2,milk=p.milk*20000,transport=p.sales*p.transport,gross=revenue-milk-mData.maintenance-mData.depreciation,bonus=Math.round(Math.max(0,gross)*.05),principal=p.loan/Math.max(1,p.term),interest=p.loan*.1,pre=gross-transport-p.market-bonus-10000-p.rent-interest,tax=Math.round(Math.max(0,pre)*.1),cashBefore=100000+p.loan-mData.machine-milk-p.market,closing=100000+p.loan+revenue-mData.machine-milk-p.market-p.rent-mData.maintenance-transport-10000-bonus-principal-interest-tax,unsold=Math.max(0,p.production-p.sales),warnings=[];if(!machines[p.machineNo])warnings.push('Enter a machine number from 1 to 6');if(p.production>mData.capacity)warnings.push('Production exceeds machine capacity');if(p.production>p.milk*20000)warnings.push('Production exceeds milk available');if(p.requested>p.production)warnings.push('Requested sales exceed production');if(cashBefore<0)warnings.push('Cash becomes negative before sales');if(closing<0)warnings.push('Closing cash is negative');if(p.production&&unsold/p.production>.2)warnings.push('More than 20% production is unsold');return{revenue,milk,transport,bonus,principal,interest,pre,tax,closing,cashBefore,unsold,warnings,netBook:Math.max(0,mData.machine-mData.depreciation),debt:Math.max(0,p.loan-principal),mData}}
function renderInputs(name){document.querySelector('#'+name+'Inputs').innerHTML=fields.map(([key,label])=>`<label>${label}<input type=number step=any data-plan=${name} data-key=${key} value=${plans[name][key]}></label>`).join('')}
function renderPlan(name){let p=plans[name],r=calc(p);document.querySelector('#'+name+'Result').innerHTML=`<div class=row><span>Machine ${p.machineNo||'?'}</span><b>${r.mData.capacity.toLocaleString()} units capacity</b></div><div class=row><span>Net profit / loss</span><b>${money(r.pre-r.tax)}</b></div><div class=row><span>Closing cash</span><b>${money(r.closing)}</b></div><div class=row><span>Unsold ice cream</span><b>${r.unsold.toLocaleString()}</b></div><div class=row><span>Loan payment</span><b>${money(r.principal+r.interest)}</b></div><p class="${r.warnings.length?'warning':'good'}">${r.warnings.length?'Risk: '+r.warnings.join(' · '):'No major warning.'}</p>`;return r}
function render(){const a=renderPlan('safe'),b=renderPlan('growth'),pick=a.warnings.length<=b.warnings.length?'Plan A · Safe winter':'Plan B · Growth winter';comparison.innerHTML=`<p class="good"><b>Recommendation: ${pick}</b>. Change actual sales allocation to test a low-sales outcome before you decide.</p>`;renderBalance()}
function renderBalance(){let name=balancePlan.value,p=plans[name],r=calc(p),assets=r.closing+r.netBook,equity=assets-r.debt;balance.innerHTML=`<div>Cash<b>${money(r.closing)}</b></div><div>Machines net value<b>${money(r.netBook)}</b></div><div>Outstanding loan<b>${money(r.debt)}</b></div><div>Owner equity<b>${money(equity)}</b></div>`}
document.addEventListener('input',e=>{if(!e.target.dataset.plan)return;plans[e.target.dataset.plan][e.target.dataset.key]=num(e.target.value);render()});balancePlan.onchange=renderBalance;chatForm.onsubmit=e=>{e.preventDefault();let q=question.value.toLowerCase(),a=calc(plans.safe),b=calc(plans.growth),answer=q.includes('cash')?`Plan A closing cash is ${money(a.closing)}. Plan B closing cash is ${money(b.closing)}.`:q.includes('profit')?`Plan A profit is ${money(a.pre-a.tax)}. Plan B profit is ${money(b.pre-b.tax)}.`:q.includes('loan')?`Plan A loan remaining is ${money(a.debt)}. Plan B loan remaining is ${money(b.debt)}.`:`Plan A has ${a.warnings.length} warning(s). Plan B has ${b.warnings.length} warning(s). The option with fewer warnings is safer.`;chat.innerHTML+=`<p><b>You:</b> ${question.value}</p><p><b>Assistant:</b> ${answer}</p>`;question.value=''};renderInputs('safe');renderInputs('growth');render();
